# Generated by Django 3.2 on 2022-07-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('stu_pin_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('stu_state', models.CharField(blank=True, max_length=20, null=True)),
                ('student_city', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'student_address',
            },
        ),
        migrations.CreateModel(
            name='StudentBranchDetails',
            fields=[
                ('stu_branch', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subjects', models.IntegerField(blank=True, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_branch_details',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('stu_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(blank=True, max_length=20, null=True)),
                ('stu_branch', models.ForeignKey(blank=True, db_column='stu_branch', null=True, on_delete=django.db.models.deletion.CASCADE, to='dj_app.studentbranchdetails')),
                ('stu_pin_code', models.ForeignKey(blank=True, db_column='stu_pin_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='dj_app.studentaddress')),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
    ]
