version: '3'

services:
    djangoweb:
      image: sanjeevasimply/dj_postgres
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "80:8000"
      environment:
       - POSTGRES_DB=dj_postgres_db
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=${PG_password}
       - POSTGRES_HOST=${RDS_host}
